#!/usr/bin/env python3
"""
fontconv.py — BDF bitmap font -> stark_gfx 1bpp C table (TASKS.md STARK-0014).

Deterministic by construction: no timestamps, no environment-dependent
output, glyphs in code-point order. Re-running it on the same input
regenerates a byte-identical file (scripts/check.sh verifies this).

  fontconv.py subset   SRC.bdf OUT.bdf --first 0x20 --last 0x7E
      Copy SRC's header (properties included — COPYRIGHT stays with the
      glyphs) and only the glyphs in [first, last], sorted, with CHARS fixed.

  fontconv.py generate SRC.bdf OUT.c --name gfx_font_mono16 \
          --cell 8x16 --baseline 13 --first 0x20 --last 0x7E --fallback 0x3F
      Place every glyph in a cell of the given size with its baseline on the
      given row (counted from the cell top) and emit the gfx_font_t table:
      row-major rows of ceil(w/8) bytes, most significant bit = leftmost.
"""
import argparse
import sys
from pathlib import Path


def parse_bdf(text):
    """Return (header_lines, {encoding: glyph_lines}) where glyph_lines run
    from STARTCHAR to ENDCHAR inclusive."""
    lines = text.splitlines()
    header, glyphs, i = [], {}, 0
    while i < len(lines) and not lines[i].startswith("STARTCHAR"):
        if not lines[i].startswith("CHARS "):
            header.append(lines[i])
        i += 1
    while i < len(lines):
        if lines[i].startswith("STARTCHAR"):
            start = i
            while not lines[i].startswith("ENDCHAR"):
                i += 1
            block = lines[start : i + 1]
            enc = next(int(l.split()[1]) for l in block if l.startswith("ENCODING "))
            glyphs[enc] = block
        i += 1
    return header, glyphs


def glyph_rows(block):
    """(bbx_w, bbx_h, bbx_xoff, bbx_yoff, [row ints, MSB-aligned to the row width])"""
    bbx = next(l for l in block if l.startswith("BBX ")).split()[1:]
    w, h, xoff, yoff = (int(v) for v in bbx)
    b = block.index("BITMAP")
    rows = [int(r, 16) for r in block[b + 1 : b + 1 + h]]
    return w, h, xoff, yoff, rows


def cmd_subset(a):
    header, glyphs = parse_bdf(Path(a.src).read_text())
    keep = [e for e in sorted(glyphs) if a.first <= e <= a.last]
    missing = [e for e in range(a.first, a.last + 1) if e not in glyphs]
    if missing:
        sys.exit(f"source lacks glyphs: {', '.join(f'U+{e:04X}' for e in missing)}")
    out = header + [f"CHARS {len(keep)}"]
    for e in keep:
        out += glyphs[e]
    out.append("ENDFONT")
    Path(a.out).write_text("\n".join(out) + "\n")


def c_char(e):
    c = chr(e)
    return "' '" if c == " " else f"'{c}'"


def cmd_generate(a):
    cell_w, cell_h = (int(v) for v in a.cell.split("x"))
    bytes_per_row = (cell_w + 7) // 8
    header, glyphs = parse_bdf(Path(a.src).read_text())
    if not a.first <= a.fallback <= a.last:
        sys.exit("fallback must be inside [first, last]")

    table = []
    for e in range(a.first, a.last + 1):
        if e not in glyphs:
            sys.exit(f"source lacks glyph U+{e:04X}")
        w, h, xoff, yoff, rows = glyph_rows(glyphs[e])
        top = a.baseline - (yoff + h)
        if xoff < 0 or xoff + w > cell_w or top < 0 or top + h > cell_h:
            sys.exit(f"U+{e:04X} ({w}x{h}{xoff:+}{yoff:+}) does not fit the {a.cell} cell")
        src_bits = ((w + 7) // 8) * 8
        cell = [0] * cell_h
        for r, v in enumerate(rows):
            # BDF rows are MSB-aligned in whole bytes; move to the cell column.
            cell[top + r] = (v << (bytes_per_row * 8 - src_bits)) >> xoff
        data = []
        for v in cell:
            data += [(v >> (8 * (bytes_per_row - 1 - k))) & 0xFF for k in range(bytes_per_row)]
        table.append((e, data))

    src_name = Path(a.src).as_posix()
    out = [
        "/*",
        f" * {Path(a.out).name} — GENERATED by tools/fontconv.py; do not edit.",
        f" * Source: {src_name}",
        " * (provenance and licence: components/stark_gfx/fonts/README.md).",
        f" * U+{a.first:04X}..U+{a.last:04X} in {cell_w}x{cell_h} cells, baseline on row"
        f" {a.baseline}, fallback U+{a.fallback:04X}.",
        " */",
        '#include "gfx_font.h"',
        "",
        "/* Generated table, one glyph per line: kept out of clang-format. */",
        "/* clang-format off */",
        "static const uint8_t k_bits[] = {",
    ]
    for e, data in table:
        out.append("    " + ", ".join(f"0x{b:02X}" for b in data) + f", /* U+{e:04X} {c_char(e)} */")
    out += [
        "};",
        "/* clang-format on */",
        "",
        f"const gfx_font_t {a.name} = {{",
        f"    .w = {cell_w},",
        f"    .h = {cell_h},",
        f"    .first = 0x{a.first:02X},",
        f"    .last = 0x{a.last:02X},",
        f"    .fallback = 0x{a.fallback:02X},",
        "    .bits = k_bits,",
        "};",
    ]
    Path(a.out).write_text("\n".join(out) + "\n")


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    num = lambda s: int(s, 0)

    s = sub.add_parser("subset")
    s.add_argument("src")
    s.add_argument("out")
    s.add_argument("--first", type=num, required=True)
    s.add_argument("--last", type=num, required=True)
    s.set_defaults(fn=cmd_subset)

    g = sub.add_parser("generate")
    g.add_argument("src")
    g.add_argument("out")
    g.add_argument("--name", required=True)
    g.add_argument("--cell", required=True, help="WxH, e.g. 8x16")
    g.add_argument("--baseline", type=int, required=True, help="baseline row from the cell top")
    g.add_argument("--first", type=num, required=True)
    g.add_argument("--last", type=num, required=True)
    g.add_argument("--fallback", type=num, required=True)
    g.set_defaults(fn=cmd_generate)

    a = p.parse_args()
    a.fn(a)


if __name__ == "__main__":
    main()
